// <auto-generated />
using System;
using Enqueuer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Enqueuer.Persistence.Migrations
{
    [DbContext(typeof(EnqueuerContext))]
    [Migration("20230330121918_AddedPositionsReferenceTable")]
    partial class AddedPositionsReferenceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Enqueuer.Persistence.Models.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Enqueuer.Persistence.Models.Position", b =>
                {
                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("Enqueuer.Persistence.Models.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GroupId");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("Enqueuer.Persistence.Models.QueueMember", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "QueueId");

                    b.HasIndex("QueueId");

                    b.ToTable("QueueMember");
                });

            modelBuilder.Entity("Enqueuer.Persistence.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<long>("GroupsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MembersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupsId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("Enqueuer.Persistence.Models.Queue", b =>
                {
                    b.HasOne("Enqueuer.Persistence.Models.User", "Creator")
                        .WithMany("CreatedQueues")
                        .HasForeignKey("CreatorId");

                    b.HasOne("Enqueuer.Persistence.Models.Group", "Group")
                        .WithMany("Queues")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Enqueuer.Persistence.Models.QueueMember", b =>
                {
                    b.HasOne("Enqueuer.Persistence.Models.Queue", "Queue")
                        .WithMany("Members")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enqueuer.Persistence.Models.User", "User")
                        .WithMany("ParticipatesIn")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Queue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("Enqueuer.Persistence.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enqueuer.Persistence.Models.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Enqueuer.Persistence.Models.Group", b =>
                {
                    b.Navigation("Queues");
                });

            modelBuilder.Entity("Enqueuer.Persistence.Models.Queue", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Enqueuer.Persistence.Models.User", b =>
                {
                    b.Navigation("CreatedQueues");

                    b.Navigation("ParticipatesIn");
                });
#pragma warning restore 612, 618
        }
    }
}
