//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enqueuer.Telegram.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enqueuer.Telegram.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I want to leave.
        /// </summary>
        internal static string Callback_DequeueMe_AgreeToDequeue_Button {
            get {
                return ResourceManager.GetString("Callback_DequeueMe_AgreeToDequeue_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to leave the &lt;b&gt;&apos;{0}&apos;&lt;/b&gt; queue?.
        /// </summary>
        internal static string Callback_DequeueMe_AreYouSureToBeDequeued_Message {
            get {
                return ResourceManager.GetString("Callback_DequeueMe_AreYouSureToBeDequeued_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed from the &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; queue!.
        /// </summary>
        internal static string Callback_DequeueMe_Success_Message {
            get {
                return ResourceManager.GetString("Callback_DequeueMe_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve already dequeued from the &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; queue..
        /// </summary>
        internal static string Callback_DequeueMe_UserDoesNotParticipate_Message {
            get {
                return ResourceManager.GetString("Callback_DequeueMe_UserDoesNotParticipate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First available.
        /// </summary>
        internal static string Callback_Enqueue_FirstAvailable_Button {
            get {
                return ResourceManager.GetString("Callback_Enqueue_FirstAvailable_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This queue has been deleted..
        /// </summary>
        internal static string Callback_Enqueue_QueueHasBeenDeleted_Message {
            get {
                return ResourceManager.GetString("Callback_Enqueue_QueueHasBeenDeleted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an available position in queue &lt;b&gt;&apos;{0}&apos;&lt;/b&gt;:.
        /// </summary>
        internal static string Callback_Enqueue_SelectPosition_Message {
            get {
                return ResourceManager.GetString("Callback_Enqueue_SelectPosition_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose another.
        /// </summary>
        internal static string Callback_EnqueueAt_PositionIsReserved_ChooseAnother_Button {
            get {
                return ResourceManager.GetString("Callback_EnqueueAt_PositionIsReserved_ChooseAnother_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; in queue &apos;&lt;b&gt;{1}&lt;/b&gt;&apos; is reserved. Please, reserve other position..
        /// </summary>
        internal static string Callback_EnqueueAt_PositionIsReserved_Message {
            get {
                return ResourceManager.GetString("Callback_EnqueueAt_PositionIsReserved_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; is now dynamic. Please, return and press the &apos;First available&apos; button..
        /// </summary>
        internal static string Callback_EnqueueAt_QueueIsDynamicButPositionIsSpecified_Message {
            get {
                return ResourceManager.GetString("Callback_EnqueueAt_QueueIsDynamicButPositionIsSpecified_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All possible positions in queue &lt;b&gt;&apos;{0}&apos; are reserved. Please, wait untill someone leaves to join..
        /// </summary>
        internal static string Callback_EnqueueAt_QueueIsFull_Message {
            get {
                return ResourceManager.GetString("Callback_EnqueueAt_QueueIsFull_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added to the queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; on position &lt;b&gt;{1}&lt;/b&gt;!.
        /// </summary>
        internal static string Callback_EnqueueAt_Success_Message {
            get {
                return ResourceManager.GetString("Callback_EnqueueAt_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already participating in queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;. To change your position, please, dequeue yourself first..
        /// </summary>
        internal static string Callback_EnqueueAt_UserAlreadyParticipates_Message {
            get {
                return ResourceManager.GetString("Callback_EnqueueAt_UserAlreadyParticipates_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This queue has been deleted. Please, create a new one to participate in..
        /// </summary>
        internal static string Callback_EnqueueMe_QueueHasBeenDeleted_Message {
            get {
                return ResourceManager.GetString("Callback_EnqueueMe_QueueHasBeenDeleted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added to queue &apos;{0}&apos; at the &apos;{1}&apos; position!.
        /// </summary>
        internal static string Callback_EnqueueMe_SuccessfullyEnqueued_Alert {
            get {
                return ResourceManager.GetString("Callback_EnqueueMe_SuccessfullyEnqueued_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already participating in queue &apos;{0}&apos;!.
        /// </summary>
        internal static string Callback_EnqueueMe_UserAlreadyParticipates_Alert {
            get {
                return ResourceManager.GetString("Callback_EnqueueMe_UserAlreadyParticipates_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat has no queues. Are you thinking of creating one?.
        /// </summary>
        internal static string Callback_GetChat_ChatHasNoQueues_Message {
            get {
                return ResourceManager.GetString("Callback_GetChat_ChatHasNoQueues_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n&lt;i&gt;Currently, you can create queues only by writting the &apos;&lt;b&gt;/createqueue&lt;/b&gt;&apos; command in this chat, but I&apos;ll learn how to create them in direct messages soon!&lt;/i&gt;.
        /// </summary>
        internal static string Callback_GetChat_DisplayQueueList_PostScriptum_Message {
            get {
                return ResourceManager.GetString("Callback_GetChat_DisplayQueueList_PostScriptum_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat has these queues. You can manage any one of them by selecting it..
        /// </summary>
        internal static string Callback_GetChat_DisplayQueuesList_Message {
            get {
                return ResourceManager.GetString("Callback_GetChat_DisplayQueuesList_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dequeue me.
        /// </summary>
        internal static string Callback_GetQueue_DequeueMe_Button {
            get {
                return ResourceManager.GetString("Callback_GetQueue_DequeueMe_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue me.
        /// </summary>
        internal static string Callback_GetQueue_EnqueueMe_Button {
            get {
                return ResourceManager.GetString("Callback_GetQueue_EnqueueMe_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &lt;b&gt;&apos;{0}&apos;&lt;/b&gt; has these participants:\n.
        /// </summary>
        internal static string Callback_GetQueue_ListQueueMembers_Message {
            get {
                return ResourceManager.GetString("Callback_GetQueue_ListQueueMembers_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue is &lt;i&gt;dynamic&lt;/i&gt;.
        /// </summary>
        internal static string Callback_GetQueue_ListQueueMembers_QueueIsDynamic_PostScriptum_Message {
            get {
                return ResourceManager.GetString("Callback_GetQueue_ListQueueMembers_QueueIsDynamic_PostScriptum_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &lt;b&gt;&apos;{0}&apos;&lt;/b&gt; has no participants..
        /// </summary>
        internal static string Callback_GetQueue_ListQueueMembers_QueueIsEmpty_Message {
            get {
                return ResourceManager.GetString("Callback_GetQueue_ListQueueMembers_QueueIsEmpty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make dynamic.
        /// </summary>
        internal static string Callback_GetQueue_MakeQueueDynamic_Button {
            get {
                return ResourceManager.GetString("Callback_GetQueue_MakeQueueDynamic_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make static.
        /// </summary>
        internal static string Callback_GetQueue_MakeQueueStatic_Button {
            get {
                return ResourceManager.GetString("Callback_GetQueue_MakeQueueStatic_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove queue.
        /// </summary>
        internal static string Callback_GetQueue_RemoveQueue_Button {
            get {
                return ResourceManager.GetString("Callback_GetQueue_RemoveQueue_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap positions.
        /// </summary>
        internal static string Callback_GetQueue_SwapPositions_Button {
            get {
                return ResourceManager.GetString("Callback_GetQueue_SwapPositions_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know that you do participate in these chats. If one of the chats is not presented, please write any command in this chat, and I&apos;ll notice you there..
        /// </summary>
        internal static string Callback_ListChats_DisplayChatsList_Message {
            get {
                return ResourceManager.GetString("Callback_ListChats_DisplayChatsList_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I haven&apos;t seen you before. Please, write any command in any chat with me, and I&apos;ll notice you there..
        /// </summary>
        internal static string Callback_ListChats_UserDoesNotParticipateInAnyGroup_Message {
            get {
                return ResourceManager.GetString("Callback_ListChats_UserDoesNotParticipateInAnyGroup_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue me!.
        /// </summary>
        internal static string Message_CreateQueueCommand_PublicChat_EnqueueMe_Button {
            get {
                return ResourceManager.GetString("Message_CreateQueueCommand_PublicChat_EnqueueMe_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat has reached its maximum number of queues. Please remove one using the &apos;&lt;b&gt;/removequeue&lt;/b&gt;&apos; command before adding a new one..
        /// </summary>
        internal static string Message_CreateQueueCommand_PublicChat_MaxNumberOfQueuesReached_Message {
            get {
                return ResourceManager.GetString("Message_CreateQueueCommand_PublicChat_MaxNumberOfQueuesReached_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a queue with only a number in its name. Please add some nice words..
        /// </summary>
        internal static string Message_CreateQueueCommand_PublicChat_OnlyNumberInQueueName_Message {
            get {
                return ResourceManager.GetString("Message_CreateQueueCommand_PublicChat_OnlyNumberInQueueName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat already has a queue named &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;. Please, use some other name for this queue or delete the existing one using &apos;&lt;b&gt;/removequeue&lt;/b&gt;&apos;..
        /// </summary>
        internal static string Message_CreateQueueCommand_PublicChat_QueueAlreadyExists_Message {
            get {
                return ResourceManager.GetString("Message_CreateQueueCommand_PublicChat_QueueAlreadyExists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a new queue, please write the command this way: &apos;&lt;b&gt;/createqueue&lt;/b&gt; &lt;i&gt;[queue_name]&lt;/i&gt;&apos;..
        /// </summary>
        internal static string Message_CreateQueueCommand_PublicChat_QueueNameIsNotProvided_Message {
            get {
                return ResourceManager.GetString("Message_CreateQueueCommand_PublicChat_QueueNameIsNotProvided_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This queue name is too long. Please, provide it with a name shorter than 50 symbols..
        /// </summary>
        internal static string Message_CreateQueueCommand_PublicChat_QueueNameIsTooLong_Message {
            get {
                return ResourceManager.GetString("Message_CreateQueueCommand_PublicChat_QueueNameIsTooLong_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created a new queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;!.
        /// </summary>
        internal static string Message_CreateQueueCommand_PublicChat_SuccessfullyCreatedQueue_Message {
            get {
                return ResourceManager.GetString("Message_CreateQueueCommand_PublicChat_SuccessfullyCreatedQueue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no queue with name &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;. You can get list of chat queues using &apos;&lt;b&gt;/queue&lt;/b&gt;&apos; command..
        /// </summary>
        internal static string Message_DequeueCommand_PublicChat_QueueDoesNotExist_Message {
            get {
                return ResourceManager.GetString("Message_DequeueCommand_PublicChat_QueueDoesNotExist_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the command this way: &apos;/&lt;b&gt;dequeue&lt;/b&gt; &lt;i&gt;[queue_name]&lt;/i&gt;&apos;..
        /// </summary>
        internal static string Message_DequeueCommand_PublicChat_QueueNameIsNotProvided_Message {
            get {
                return ResourceManager.GetString("Message_DequeueCommand_PublicChat_QueueNameIsNotProvided_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed from queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;!.
        /// </summary>
        internal static string Message_DequeueCommand_PublicChat_SuccessfullyDequeued_Message {
            get {
                return ResourceManager.GetString("Message_DequeueCommand_PublicChat_SuccessfullyDequeued_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not participating in queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;..
        /// </summary>
        internal static string Message_DequeueCommand_PublicChat_UserDoesNotParticipate_Message {
            get {
                return ResourceManager.GetString("Message_DequeueCommand_PublicChat_UserDoesNotParticipate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, use positive numbers for user position, but not greater than 500..
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_InvalidPositionSpecified_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_InvalidPositionSpecified_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; in the queue &apos;&lt;b&gt;{1}&lt;/b&gt;&apos; is reserved. Please, reserve other position..
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_PositionIsReserved_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_PositionIsReserved_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; is dynamic - you can enqueue yourself only at the end of the queue..
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_PositionSpecified_DynamicQueue_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_PositionSpecified_DynamicQueue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no queue with the name &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;. You can get list of chat queues using &apos;&lt;b&gt;/queue&lt;/b&gt;&apos; command..
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_QueueDoesNotExist_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_QueueDoesNotExist_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be enqueued, please write the command this way: &apos;&lt;b&gt;/enqueue&lt;/b&gt; &lt;i&gt;[queue_name] [position(optional)]&lt;/i&gt;&apos;..
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_QueueNameIsNotProvided_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_QueueNameIsNotProvided_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added to the queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; on position &lt;b&gt;{1}&lt;/b&gt;!.
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_SuccessfullyAddedOnPosition_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_SuccessfullyAddedOnPosition_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already participating in queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;..
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_UserAlreadyParticipates_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_UserAlreadyParticipates_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the list of available commands with short description:
        ///&lt;b&gt;/start&lt;/b&gt; - get introducing message
        ///&lt;b&gt;/help&lt;/b&gt; - get bot help
        ///&lt;b&gt;/queue&lt;/b&gt; - list chat queues or get info about one of them
        ///&lt;b&gt;/createqueue&lt;/b&gt; - create new queue
        ///&lt;b&gt;/enqueue&lt;/b&gt; - add yourself to the end of a queue or to a specified position
        ///&lt;b&gt;/dequeue&lt;/b&gt; - remove yourself from a queue
        ///&lt;b&gt;/removequeue&lt;/b&gt; - delete a queue
        ///To get slightly more detailed info about one of them, write the appropriate command..
        /// </summary>
        internal static string Message_HelpCommand_Message {
            get {
                return ResourceManager.GetString("Message_HelpCommand_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • {0}.
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_DisplayQueue_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_DisplayQueue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}) &lt;b&gt;{1}&lt;/b&gt;.
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_DisplayQueueParticipant_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_DisplayQueueParticipant_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; has these participants:\n.
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_ListQueueParticipants_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_ListQueueParticipants_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat has these queues:\n.
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_ListQueues_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_ListQueues_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat has no queues. To create new one write &apos;&lt;b&gt;/createqueue&lt;/b&gt; &lt;i&gt;queue_name&lt;/i&gt;&apos;..
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_ListQueues_NoQueues_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_ListQueues_NoQueues_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get info about one of them write &apos;&lt;b&gt;/queue&lt;/b&gt; &lt;i&gt;[queue_name]&lt;/i&gt;&apos;..
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_ListQueues_PostScriptum_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_ListQueues_PostScriptum_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat has no queue with name &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;..
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_QueueDoesNotExist_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_QueueDoesNotExist_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; has no participants..
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_QueueIsEmpty_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_QueueIsEmpty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no queue with name &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;. You can get list of chat queues using &apos;&lt;b&gt;/queue&lt;/b&gt;&apos; command..
        /// </summary>
        internal static string Message_RemoveQueueCommand_PublicChat_QueueDoesNotExist_Message {
            get {
                return ResourceManager.GetString("Message_RemoveQueueCommand_PublicChat_QueueDoesNotExist_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete queue, please write command this way: &apos;&lt;b&gt;/removequeue&lt;/b&gt; &lt;i&gt;[queue_name]&lt;/i&gt;&apos;..
        /// </summary>
        internal static string Message_RemoveQueueCommand_PublicChat_QueueNameIsNotProvided_Message {
            get {
                return ResourceManager.GetString("Message_RemoveQueueCommand_PublicChat_QueueNameIsNotProvided_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;!.
        /// </summary>
        internal static string Message_RemoveQueueCommand_PublicChat_SuccessfullyRemovedQueue_Message {
            get {
                return ResourceManager.GetString("Message_RemoveQueueCommand_PublicChat_SuccessfullyRemovedQueue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;. It can be deleted only by it&apos;s creator or chat administrators..
        /// </summary>
        internal static string Message_RemoveQueueCommand_PublicChat_UserHasNoRightToDelete_Message {
            get {
                return ResourceManager.GetString("Message_RemoveQueueCommand_PublicChat_UserHasNoRightToDelete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View chats.
        /// </summary>
        internal static string Message_StartCommand_PrivateChat_ListChats_Button {
            get {
                return ResourceManager.GetString("Message_StartCommand_PrivateChat_ListChats_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there! I&apos;m &lt;b&gt;Enqueuer Bot&lt;/b&gt;, the master of creating and managing queues.
        ///And your personal queue manager too!
        ///Start by pressing the button below:.
        /// </summary>
        internal static string Message_StartCommand_PrivateChat_Message {
            get {
                return ResourceManager.GetString("Message_StartCommand_PrivateChat_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there! I&apos;m &lt;b&gt;Enqueuer Bot&lt;/b&gt;, the master of creating and managing queues.
        ///To get the list of commands, write &apos;&lt;b&gt;/help&lt;/b&gt;&apos;.
        ///&lt;i&gt;Please, message this guy (@hopelite) to get help, give feedback or report a bug.&lt;/i&gt;.
        /// </summary>
        internal static string Message_StartCommand_PublicChat_Message {
            get {
                return ResourceManager.GetString("Message_StartCommand_PublicChat_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot does not support the &apos;{0}&apos; command..
        /// </summary>
        internal static string Message_UnsupportedCommand_Message {
            get {
                return ResourceManager.GetString("Message_UnsupportedCommand_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot does not support commands in private chats except &apos;&lt;b&gt;/start&lt;/b&gt;&apos;. Please, use interface it provides..
        /// </summary>
        internal static string Message_UnsupportedCommand_PrivateChat_Message {
            get {
                return ResourceManager.GetString("Message_UnsupportedCommand_PrivateChat_Message", resourceCulture);
            }
        }
    }
}
