//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enqueuer.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enqueuer.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, use positive numbers for user position, but not greater than 500..
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_InvalidPositionSpecified_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_InvalidPositionSpecified_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; in the queue &apos;&lt;b&gt;{1}&lt;/b&gt;&apos; is reserved. Please, reserve other position..
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_PositionIsReserved_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_PositionIsReserved_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; is dynamic - you can enqueue yourself only at the end of the queue..
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_PositionSpecified_DynamicQueue_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_PositionSpecified_DynamicQueue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no queue with the name &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;. You can get list of chat queues using &apos;&lt;b&gt;/queue&lt;/b&gt;&apos; command..
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_QueueDoesNotExist_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_QueueDoesNotExist_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be enqueued, please write the command this way: &apos;&lt;b&gt;/enqueue&lt;/b&gt; &lt;i&gt;[queue_name] [position(optional)]&lt;/i&gt;&apos;..
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_QueueNameIsNotProvided_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_QueueNameIsNotProvided_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added to the queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; on position &lt;b&gt;{1}&lt;/b&gt;!.
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_SuccessfullyAddedOnPosition_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_SuccessfullyAddedOnPosition_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already participating in queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;..
        /// </summary>
        internal static string Message_EnqueueCommand_PublicChat_UserAlreadyParticipates_Message {
            get {
                return ResourceManager.GetString("Message_EnqueueCommand_PublicChat_UserAlreadyParticipates_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the list of available commands with short description:
        ///&lt;b&gt;/start&lt;/b&gt; - get introducing message
        ///&lt;b&gt;/help&lt;/b&gt; - get bot help
        ///&lt;b&gt;/queue&lt;/b&gt; - list chat queues or get info about one of them
        ///&lt;b&gt;/createqueue&lt;/b&gt; - create new queue
        ///&lt;b&gt;/enqueue&lt;/b&gt; - add yourself to the end of a queue or to a specified position
        ///&lt;b&gt;/dequeue&lt;/b&gt; - remove yourself from a queue
        ///&lt;b&gt;/removequeue&lt;/b&gt; - delete a queue
        ///To get slightly more detailed info about one of them, write the appropriate command..
        /// </summary>
        internal static string Message_HelpCommand_Message {
            get {
                return ResourceManager.GetString("Message_HelpCommand_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • {0}.
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_DisplayQueue_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_DisplayQueue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}) &lt;b&gt;{1}&lt;/b&gt;.
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_DisplayQueueParticipant_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_DisplayQueueParticipant_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; has these participants:\n.
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_ListQueueParticipants_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_ListQueueParticipants_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat has these queues:\n.
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_ListQueues_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_ListQueues_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat has no queues. To create new one write &apos;&lt;b&gt;/createqueue&lt;/b&gt; &lt;i&gt;queue_name&lt;/i&gt;&apos;..
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_ListQueues_NoQueues_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_ListQueues_NoQueues_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get info about one of them write &apos;&lt;b&gt;/queue&lt;/b&gt; &lt;i&gt;[queue_name]&lt;/i&gt;&apos;..
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_ListQueues_PostScriptum_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_ListQueues_PostScriptum_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat has no queue with name &apos;&lt;b&gt;{0}&lt;/b&gt;&apos;..
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_QueueDoesNotExist_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_QueueDoesNotExist_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &apos;&lt;b&gt;{0}&lt;/b&gt;&apos; has no participants..
        /// </summary>
        internal static string Message_QueueCommand_PublicChat_QueueIsEmpty_Message {
            get {
                return ResourceManager.GetString("Message_QueueCommand_PublicChat_QueueIsEmpty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View chats.
        /// </summary>
        internal static string Message_StartCommand_PrivateChat_ListChats_Button {
            get {
                return ResourceManager.GetString("Message_StartCommand_PrivateChat_ListChats_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there! I&apos;m &lt;b&gt;Enqueuer Bot&lt;/b&gt;, the master of creating and managing queues.
        ///And your personal queue manager too!
        ///Start by pressing the button below:.
        /// </summary>
        internal static string Message_StartCommand_PrivateChat_Message {
            get {
                return ResourceManager.GetString("Message_StartCommand_PrivateChat_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there! I&apos;m &lt;b&gt;Enqueuer Bot&lt;/b&gt;, the master of creating and managing queues.
        ///To get the list of commands, write &apos;&lt;b&gt;/help&lt;/b&gt;&apos;.
        ///&lt;i&gt;Please, message this guy (@hopelite) to get help, give feedback or report a bug.&lt;/i&gt;.
        /// </summary>
        internal static string Message_StartCommand_PublicChat_Message {
            get {
                return ResourceManager.GetString("Message_StartCommand_PublicChat_Message", resourceCulture);
            }
        }
    }
}
